# -*- coding: utf-8 -*-
"""spero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhiWRNiteoe34GqxkZ4ebu3ujVqj1_Ez
"""

import nltk  
nltk.download('punkt')
nltk.download('stopwords')  
from nltk.corpus import stopwords

import xlrd
file_name = 'De-identified student comments.xlsx';

import pandas as pd
df = pd.read_excel(io=file_name)
#print(df.head)

df = df.dropna(axis=0, how="any")

from nltk.tokenize import word_tokenize

positive = pd.read_excel(file_name, sheet_name='POSITIVE')
negative = pd.read_excel(file_name, sheet_name='NEGATIVE')

sent_positive = positive.to_string(index=False)
sent_negative = negative.to_string(index=False)

positive_tokens = word_tokenize(sent_positive)
negative_tokens = word_tokenize(sent_negative)

#import the nltk package
import nltk
#call the nltk downloader
nltk.download('punkt')
from nltk.stem.porter import * 

from nltk.corpus import stopwords 
from nltk.tokenize import sent_tokenize 
import re

stemmer = PorterStemmer()
stop_words = set(stopwords.words('english')) 


rows = list()
wholedata = " "

word_token = []

for row in df[['HELPFUL', 'IMPROVE']].iterrows():
    r = row[1]
    data =r.get_values()[0]
    lower = data.lower()

    reg = re.sub('[^A-Za-z0-9]+', ' ', lower) 
    word_tokens = sent_tokenize(reg) 
    word_token.append(word_tokens)

from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import PorterStemmer

porter=PorterStemmer()
stemmed_sentences = []
def stemSentence(sentence):
    token_words=word_tokenize(sentence)
    token_words
    stem_sentence=[]
    for word in token_words:
        stem_sentence.append(porter.stem(word))
        stem_sentence.append(" ")
    return "".join(stem_sentence)

for row in word_token:
  x=stemSentence(row[0])
  stemmed_sentences.append(x)
  
print(stemmed_sentences[0])

from textblob import TextBlob
!pip install stanfordnlp
#!pip install textblob vadersentiment
#from vadersentiment.vadersentiment import SentimentIntensityAnalyzer

import stanfordnlp
stanfordnlp.download('en')

nlp = stanfordnlp.Pipeline()

doc = nlp("""The prospects for Britain’s orderly withdrawal from the European Union on March 29 have receded further, even as MPs rallied to stop a no-deal scenario. An amendment to the draft bill on the termination of London’s membership of the bloc obliges Prime Minister Theresa May to renegotiate her withdrawal agreement with Brussels. A Tory backbencher’s proposal calls on the government to come up with alternatives to the Irish backstop, a central tenet of the deal Britain agreed with the rest of the EU.""")

print(doc.load_annotations)

sentence_analysis=[]  
for row in stemmed_sentences:
  analysis = TextBlob(row)
  sentence_with_sentiment=[row,analysis.sentiment]
  sentence_analysis.append(sentence_with_sentiment)
  
print(sentence_analysis)

pos_count = 0
pos_positive = 0
pos_negative = 0
for row in sentence_analysis:
   pos_count +=1
   if row[1].polarity > 0.5:
      pos_positive += 1
     
   if row[1].polarity < 0.5:
      pos_negative+=1
print(pos_count)
print(pos_correct)
print(pos_negative)



